# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d7edc2f307a575c51a80e9b92d057854679ea3c0da8f31eb3374a3f5e950521f2bbd63d4c14df3d618753d089a29b28881b890f89cd2fef1fb6b78395a87d4e

test:
  secret_key_base: 3fcfa539b00d3bccca720463824c187e7fdbe3dcd980cc957adb5d2717035770bd46db9e5f85ae99a79123015e38492ff7eede84d5796e380eb38ff9fd698b99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
